
##command 1 
SELECT * FROM department
WHERE locations = '34 Home St';

##command 2
SELECT DEPARTMENT_ID
FROM department
WHERE locations = '34 Home St';

##command 3
SELECT DEPARTMENT_NAME
FROM DEPARTMENT
WHERE DEP_PHONE_NO = '477-1212' ;

##command 4
SELECT DOCTOR_NAME
FROM DOCTOR 
WHERE DeptID = 1
GROUP BY DOCTOR_NAME
ORDER BY DOCTOR_NAME;

##command 5
SELECT DOCTOR_NAME
FROM DOCTOR 
WHERE DeptID = 1
GROUP BY DOCTOR_NAME
ORDER BY DOCTOR_NAME DESC;

##command 6
SELECT SALARY, DOCTOR_NAME
FROM DOCTOR 
GROUP BY DOCTOR_NAME
HAVING SALARY > '7000.00';

##command 7
SELECT SALARY, DOCTOR_NAME
FROM DOCTOR 
GROUP BY DOCTOR_NAME
HAVING SALARY > '7000.00' AND  SALARY < '20000.00';

##command 8
SELECT * FROM DOCTOR 
WHERE DOCTOR_NAME IN (SELECT DEPARTMENT_ID 
					  FROM DEPARTMENT  
					  WHERE DEPARTMENT_ID = '3');

##command 9
SELECT * FROM DEPARTMENT
WHERE DEPARTMENT_NAME IN (SELECT DOCTOR_NAME 
						  FROM DOCTOR  
						  WHERE DeptID = '1');
						  
						  
##command 10
SELECT doctor.DoctorID, department.DEPARTMENT_NAME, department.DEPARTMENT_ID
FROM department
INNER JOIN doctor ON doctor.DeptID=department.DEPARTMENT_ID; 


##command 11
SELECT doctor.DOCTOR_NAME, department.DEPARTMENT_NAME, PHONE_NUMBER
FROM doctor
INNER JOIN department ON doctor.DeptID=department.DEPARTMENT_ID; 